name: beltis_app
description: Beltis App Test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  internet_connection_checker: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  change_case: ^2.1.0
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  formz: ^0.7.0
  intl: ^0.18.0
  rxdart: ^0.28.0
  uuid: ^4.4.0

  timelines_plus: ^1.0.2

  # Hooks
  flutter_hooks: ^0.18.6

  # Fontes
  google_fonts: ^6.2.1

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.5.0
  shared_preferences: ^2.0.18
  logging: ^1.1.1
  path_provider: ^2.0.3

  # Firebase
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2

  # Database
  sqflite: ^2.2.6
  floor: ^1.4.1

  # Injeção de dependencia
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Rotas
  auto_route: ^8.2.0

  # Estados
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Requisições
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  jwt_decode: ^0.3.1
  retrofit: ^4.0.1
  #-Dio
  dio: ^5.0.2
  pretty_dio_logger: ^1.3.1
  fresh_dio: ^0.4.0

  # Imagem
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.5

  # Testes
  mockito: ^5.3.2
  bloc_test: ^9.1.4

  # Requisições
  retrofit_generator: ^8.1.1

  # Modelos
  json_serializable: ^6.6.1
  freezed: ^2.3.2

  # Rotas
  auto_route_generator: ^8.0.0

  # Icones
  flutter_launcher_icons: ^0.13.1

  # Banco de dados
  floor_generator: ^1.4.1



dependency_overrides:
  xml: ^6.2.2
  intl: ^0.18.0
  dio: ^5.0.2
  http: ^1.0.0

flutter_gen:
  output: lib/app/gen/
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/

scripts:
  build-clean: flutter packages pub run build_runner clean
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  generate-icons-d: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-development
  generate-icons-p: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-production
  generate-icons-s: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-staging
  generate-splash: dart run flutter_native_splash:create